name: GetScreen Windows 10 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=tahchma@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://gitlab.com/TalhaAhmedCho/get-screen-windows-rdp/-/raw/main/down.bat" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: cmd /c loop.bat
